### ISSUE TITLE
Sample App Breaks on Android version 9 usage of Reflection

### ISSUE THREAD

**Issue by keithentzeroth** [diegocarloslima/FloatingGroupExpandableListView#8]
Compiled as-is and tried to run on a device with 2.3.4

At a minimum, the manifest should be updated.

**Comment by diegocarloslima** [comment]
Hi, thanks for the feedback. Could you please post the stacktrace?

**Comment by mainer** [comment]
Hi, @keithentzeroth @diegocarloslima , I found the breaken that this app too, in sysytem version 2.3.x. this break is occur always. the reason is in AbListView in 2.3.x has not the mSelectorPosition field, @diegocarloslima  use the reflect to find the mSelectorPosition and Integer it ("mSelectorPosition = (Integer) ReflectionUtils.getFieldValue(
                    AbsListView.class, "mSelectorPosition",
                    FloatingGroupExpandableListView.this);"); so the nullpointException happened! 
and the resulution is this:
if (ReflectionUtils.getFieldValue(AbsListView.class,
                "mSelectorPosition", FloatingGroupExpandableListView.this) == null) {
            mSelectorPosition = (Integer) ReflectionUtils.getFieldValue(
                    AbsListView.class, "mMotionPosition",
                    FloatingGroupExpandableListView.this);
            SogouLog.e("TAG", "" + mSelectorPosition);
        } else {
            mSelectorPosition = (Integer) ReflectionUtils.getFieldValue(
                    AbsListView.class, "mSelectorPosition",
                    FloatingGroupExpandableListView.this);
        }

the mMotionPosition is equel the mSelectorPosition.

**Comment by diegocarloslima** [comment]
Hi mainer, thanks for your code snippet. I'll fix that asap.
